#!/usr/bin/env bash
# install_pi.sh - set up the label watcher on Raspberry Pi OS (Bookworm).
# Run with: sudo bash install_pi.sh
set -euo pipefail

DEST=/opt/mplabel
RUN_USER=${SUDO_USER:-pi}
HOME_DIR=$(getent passwd "$RUN_USER" | cut -d: -f6)
DATA_DIR="$HOME_DIR/marketplace"

echo "==> installing for user $RUN_USER, data in $DATA_DIR"

apt-get update
# cups + printer-driver-* covers most USB label printers.
# libopenjp2-7 and libjpeg are Pillow's runtime deps on Bookworm.
apt-get install -y python3 python3-venv python3-pip \
    cups cups-client usbutils \
    libopenjp2-7 libjpeg62-turbo zlib1g

echo "==> adding $RUN_USER to lp and lpadmin"
usermod -aG lp,lpadmin "$RUN_USER"

install -d -o "$RUN_USER" -g "$RUN_USER" "$DEST" "$DATA_DIR/labels"
cp -r src pyproject.toml requirements.txt "$DEST"/

# Stamp what is actually being installed. The version in pyproject.toml
# never moves and `git describe` cannot help here - the copy above brings
# no .git with it - so without this there is no way to tell a Pi running
# this week's code from one running last month's behind an unchanged
# interface, which is a failure this project has already had.
REV=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
PRINTERS_SHA=$(sha256sum src/mplabel/printers.py | cut -c1-12)
cat > "$DEST/src/mplabel/_build.py" <<EOF
# Generated by install_pi.sh. Not in git.
REV = "$REV"
PRINTERS_SHA = "$PRINTERS_SHA"
EOF
echo "==> installing $REV (printers.py $PRINTERS_SHA)"

chown -R "$RUN_USER":"$RUN_USER" "$DEST"

echo "==> python venv"
sudo -u "$RUN_USER" python3 -m venv "$DEST/venv"
sudo -u "$RUN_USER" "$DEST/venv/bin/pip" install --upgrade pip
# All four have prebuilt aarch64 wheels, so no compiling on the Pi.
sudo -u "$RUN_USER" "$DEST/venv/bin/pip" install "$DEST[sheets]"
# ...then force the package itself back in. The version in pyproject.toml
# does not move between changes, so pip sees mplabel 0.1.0 already
# installed and skips it - meaning a re-run of this script would leave the
# OLD code running. --no-deps keeps that from re-downloading the world.
sudo -u "$RUN_USER" "$DEST/venv/bin/pip" install --force-reinstall --no-deps "$DEST"

if [ ! -f /etc/mplabel.conf ]; then
    cp mplabel.conf.example /etc/mplabel.conf
    sed -i "s|/home/pi/marketplace|$DATA_DIR|" /etc/mplabel.conf
    chown "$RUN_USER":"$RUN_USER" /etc/mplabel.conf
    chmod 600 /etc/mplabel.conf
    echo "==> wrote /etc/mplabel.conf - EDIT IT before starting the service"
fi

sed -e "s|^User=.*|User=$RUN_USER|" \
    -e "s|^WorkingDirectory=.*|WorkingDirectory=$DEST|" \
    -e "s|^ExecStart=.*|ExecStart=$DEST/venv/bin/python -m mplabel run --loop|" \
    -e "s|^ReadWritePaths=.*|ReadWritePaths=$DATA_DIR|" \
    -e "s|^ProtectHome=.*|ProtectHome=false|" \
    systemd/mplabel.service > /etc/systemd/system/mplabel.service
systemctl daemon-reload

# The raw backends (escpos, tspl, zpl) need usblp, which CUPS unbinds when
# it claims a printer. Load it at boot and keep CUPS off the label printer.
if ! grep -q '^usblp' /etc/modules 2>/dev/null; then
    echo "usblp" >> /etc/modules
fi
modprobe usblp 2>/dev/null || true

cp udev/99-clabel-g4.rules /etc/udev/rules.d/
udevadm control --reload-rules && udevadm trigger || true

cat <<EOF

==> done. Next:

  1. Log out and back in, so the lp group membership takes effect.
  2. Plug in the G4 and turn it on, then:
                                     $DEST/venv/bin/python -m mplabel probe
     The G4 reports "speaks ESC/POS", but it actually speaks TSPL - the
     id string is boilerplate. Note the /dev/usb/lpN node.
  3. Tiny text-only test print:      $DEST/venv/bin/python -m mplabel selftest
     This is a few dozen bytes and no raster. If it prints, the language
     is right and only the image path is left to prove.
  4. Edit /etc/mplabel.conf          (IMAP credentials; device node if not lp0)
     NOTE: an existing /etc/mplabel.conf is never overwritten by this
     script, so after an update check printer_backend by hand - the file
     wins over the built-in default. The G4 wants tspl.
  5. Dry run, no printing:           $DEST/venv/bin/python -m mplabel check
  6. Real label:                     $DEST/venv/bin/python -m mplabel test-print
  7. Start it:                       sudo systemctl enable --now mplabel
  8. Watch it:                       journalctl -u mplabel -f

EOF
