"""A QR encoder, in the stdlib, for inventory labels.

Hand-written for the same reason `lzma1.py` and the parcel-code overlay
are: the Pi dependency list is kept short on purpose, and a QR code is a
fixed, forty-year-old specification that will not change under us. Adding
a package to draw twenty-one squares would be the convenience this repo
has already decided against twice.

Scope is deliberately narrow - versions 1 to 10, which is up to 174
alphanumeric characters at level M. An inventory code is four characters
and fits in a version 1 at the highest error correction the format has,
so the range here is headroom for a URL, not ambition.

Correctness is not taken on trust. `test_qr_matches_a_reference_encoder`
pins whole matrices generated by `segno`, an independent implementation,
across every version, error-correction level and mode this module claims
to support. segno is not a dependency of anything - it was used once to
produce the fixtures and the fixtures are what the tests compare against.
"""

# The alphanumeric set, in the order that defines each character's value.
# Note it is not ASCII order and does not contain lowercase: a string
# with a lowercase letter in it is a byte-mode string, which costs about
# 40% more capacity.
ALPHANUMERIC = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:"

MODE_ALNUM = 0b0010
MODE_BYTE = 0b0100

# Error-correction levels, in the order the format-information field
# numbers them - which is *not* increasing strength.
ECC_LEVELS = {"L": 0b01, "M": 0b00, "Q": 0b11, "H": 0b10}

# Per version: (error-correction codewords per block, [(block count,
# data codewords per block), ...]). Two groups where the blocks are not
# all the same size, which is most of them above version 4.
BLOCKS = {
    (1, "L"): (7, [(1, 19)]),    (1, "M"): (10, [(1, 16)]),
    (1, "Q"): (13, [(1, 13)]),   (1, "H"): (17, [(1, 9)]),
    (2, "L"): (10, [(1, 34)]),   (2, "M"): (16, [(1, 28)]),
    (2, "Q"): (22, [(1, 22)]),   (2, "H"): (28, [(1, 16)]),
    (3, "L"): (15, [(1, 55)]),   (3, "M"): (26, [(1, 44)]),
    (3, "Q"): (18, [(2, 17)]),   (3, "H"): (22, [(2, 13)]),
    (4, "L"): (20, [(1, 80)]),   (4, "M"): (18, [(2, 32)]),
    (4, "Q"): (26, [(2, 24)]),   (4, "H"): (16, [(4, 9)]),
    (5, "L"): (26, [(1, 108)]),  (5, "M"): (24, [(2, 43)]),
    (5, "Q"): (18, [(2, 15), (2, 16)]),
    (5, "H"): (22, [(2, 11), (2, 12)]),
    (6, "L"): (18, [(2, 68)]),   (6, "M"): (16, [(4, 27)]),
    (6, "Q"): (24, [(4, 19)]),   (6, "H"): (28, [(4, 15)]),
    (7, "L"): (20, [(2, 78)]),   (7, "M"): (18, [(4, 31)]),
    (7, "Q"): (18, [(2, 14), (4, 15)]),
    (7, "H"): (26, [(4, 13), (1, 14)]),
    (8, "L"): (24, [(2, 97)]),
    (8, "M"): (22, [(2, 38), (2, 39)]),
    (8, "Q"): (22, [(4, 18), (2, 19)]),
    (8, "H"): (26, [(4, 14), (2, 15)]),
    (9, "L"): (30, [(2, 116)]),
    (9, "M"): (22, [(3, 36), (2, 37)]),
    (9, "Q"): (20, [(4, 16), (4, 17)]),
    (9, "H"): (24, [(4, 12), (4, 13)]),
    (10, "L"): (18, [(2, 68), (2, 69)]),
    (10, "M"): (26, [(4, 43), (1, 44)]),
    (10, "Q"): (24, [(6, 19), (2, 20)]),
    (10, "H"): (28, [(6, 15), (2, 16)]),
}

# Centres of the alignment patterns. Version 1 has none; the finders are
# enough to locate a symbol that small.
ALIGNMENT = {
    1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30], 6: [6, 34],
    7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
}

MAX_VERSION = 10


class QRError(ValueError):
    """The text does not fit, or cannot be encoded in a supported mode."""


# ----------------------------------------------------------- GF(256)
#
# The field arithmetic and the Reed-Solomon encoder live in `rs.py`,
# shared with `marker.py`. This module only ever *makes* error-correction
# bytes; the marker has to use them, so the decoding half is over there.

from .rs import mul as _gf_mul          # noqa: E402  (kept for tests)
from .rs import generator as _rs_generator  # noqa: E402
from .rs import _EXP                    # noqa: E402
from .rs import encode as rs_encode      # noqa: E402


def _rs_remainder(data, degree):
    """The `degree` error-correction codewords for one block."""
    return list(rs_encode(data, degree))


# ------------------------------------------------------------ encoding

class _Bits:
    """A bit accumulator. QR is bit-packed throughout and byte-aligned
    only at the very end, so this is the whole of the plumbing."""

    def __init__(self):
        self.bits = []

    def append(self, value, length):
        for i in range(length - 1, -1, -1):
            self.bits.append((value >> i) & 1)

    def __len__(self):
        return len(self.bits)

    def to_bytes(self):
        out = bytearray()
        for i in range(0, len(self.bits), 8):
            byte = 0
            for bit in self.bits[i:i + 8]:
                byte = (byte << 1) | bit
            out.append(byte << (8 - len(self.bits[i:i + 8])) & 0xFF
                       if len(self.bits[i:i + 8]) < 8 else byte)
        return bytes(out)


def pick_mode(text):
    """Alphanumeric where the text allows it, byte otherwise.

    Numeric mode is not implemented: it would only ever be reached by an
    all-digit inventory code, and it saves two bits per three digits on a
    string of four. Not worth a second code path in something that has to
    stay readable."""
    if all(ch in ALPHANUMERIC for ch in text):
        return MODE_ALNUM
    return MODE_BYTE


def _char_count_bits(mode, version):
    """Versions 1-9 and 10 use different widths for the count field."""
    if mode == MODE_ALNUM:
        return 9 if version <= 9 else 11
    return 8 if version <= 9 else 16


def _encode_payload(text, mode, version):
    bits = _Bits()
    bits.append(mode, 4)

    if mode == MODE_ALNUM:
        bits.append(len(text), _char_count_bits(mode, version))
        # Two characters to eleven bits, base 45; a trailing odd one
        # takes six.
        for i in range(0, len(text) - 1, 2):
            pair = (ALPHANUMERIC.index(text[i]) * 45
                    + ALPHANUMERIC.index(text[i + 1]))
            bits.append(pair, 11)
        if len(text) % 2:
            bits.append(ALPHANUMERIC.index(text[-1]), 6)
    else:
        data = text.encode("utf-8")
        bits.append(len(data), _char_count_bits(mode, version))
        for byte in data:
            bits.append(byte, 8)
    return bits


def _data_capacity_bits(version, ecl):
    _ec, groups = BLOCKS[(version, ecl)]
    return sum(count * size for count, size in groups) * 8


def choose_version(text, ecl, mode=None, min_version=1):
    """The smallest version that holds `text` at this correction level."""
    mode = pick_mode(text) if mode is None else mode
    for version in range(min_version, MAX_VERSION + 1):
        need = len(_encode_payload(text, mode, version))
        if need + 4 <= _data_capacity_bits(version, ecl):
            return version
        # +4 leaves room for the terminator; a payload that fills the
        # symbol exactly is legal, but only if it needs no terminator at
        # all, and the check below in `encode` handles that case.
        if need <= _data_capacity_bits(version, ecl):
            return version
    raise QRError(
        f"{len(text)} characters do not fit in a version {MAX_VERSION} "
        f"symbol at level {ecl}")


def _codewords(text, version, ecl, mode):
    """Data plus error correction, interleaved as the symbol wants them."""
    capacity = _data_capacity_bits(version, ecl)
    bits = _encode_payload(text, mode, version)
    if len(bits) > capacity:
        raise QRError("payload does not fit the chosen version")

    # Terminator, up to four zero bits, then pad to a byte boundary.
    bits.append(0, min(4, capacity - len(bits)))
    if len(bits) % 8:
        bits.append(0, 8 - len(bits) % 8)

    data = bytearray(bits.to_bytes())
    # The specified pad bytes, alternating, until the symbol is full.
    for i in range((capacity // 8) - len(data)):
        data.append(0xEC if i % 2 == 0 else 0x11)

    ec_per_block, groups = BLOCKS[(version, ecl)]
    blocks, ec_blocks, pos = [], [], 0
    for count, size in groups:
        for _ in range(count):
            block = bytes(data[pos:pos + size])
            pos += size
            blocks.append(block)
            ec_blocks.append(_rs_remainder(block, ec_per_block))

    # Interleaved: the first codeword of every block, then the second,
    # and so on - which is what spreads a scratch across blocks instead
    # of destroying one of them.
    out = bytearray()
    for i in range(max(len(b) for b in blocks)):
        for block in blocks:
            if i < len(block):
                out.append(block[i])
    for i in range(ec_per_block):
        for block in ec_blocks:
            out.append(block[i])
    return bytes(out)


# ------------------------------------------------------------- drawing

def _new_matrix(size):
    return [[None] * size for _ in range(size)]


def _place_finder(m, row, col):
    size = len(m)
    for r in range(-1, 8):
        for c in range(-1, 8):
            rr, cc = row + r, col + c
            if not (0 <= rr < size and 0 <= cc < size):
                continue
            # The 7x7 eye, then the one-module quiet ring around it.
            dark = (0 <= r < 7 and 0 <= c < 7
                    and (r in (0, 6) or c in (0, 6)
                         or (2 <= r <= 4 and 2 <= c <= 4)))
            m[rr][cc] = 1 if dark else 0


def _place_alignment(m, version):
    centres = ALIGNMENT[version]
    last = len(m) - 8
    for row in centres:
        for col in centres:
            # The three corners hold finders instead.
            if (row < 8 and col < 8) or (row < 8 and col > last) \
                    or (row > last and col < 8):
                continue
            for r in range(-2, 3):
                for c in range(-2, 3):
                    m[row + r][col + c] = \
                        1 if max(abs(r), abs(c)) != 1 else 0


def _place_timing(m):
    for i in range(8, len(m) - 8):
        bit = 1 if i % 2 == 0 else 0
        if m[6][i] is None:
            m[6][i] = bit
        if m[i][6] is None:
            m[i][6] = bit


def _reserve_format(m, version):
    size = len(m)
    for i in range(9):
        if m[8][i] is None:
            m[8][i] = 0
        if m[i][8] is None:
            m[i][8] = 0
    for i in range(8):
        if m[8][size - 1 - i] is None:
            m[8][size - 1 - i] = 0
        if m[size - 1 - i][8] is None:
            m[size - 1 - i][8] = 0
    # Always dark, and it is not part of the format field.
    m[size - 8][8] = 1
    if version >= 7:
        for i in range(6):
            for j in range(3):
                m[size - 11 + j][i] = 0
                m[i][size - 11 + j] = 0


def _place_data(m, codewords):
    """Two modules wide, bottom to top and back again, skipping column 6.

    The zig-zag is the part that looks wrong when written from memory, so
    it is spelled out: columns are walked in pairs from the right, the
    direction flips at each pair, and the vertical timing column is not a
    column for this purpose at all."""
    size = len(m)
    bits = [(byte >> i) & 1 for byte in codewords for i in range(7, -1, -1)]
    idx = 0
    col = size - 1
    upward = True
    while col > 0:
        if col == 6:
            col -= 1
        rows = range(size - 1, -1, -1) if upward else range(size)
        for row in rows:
            for c in (col, col - 1):
                if m[row][c] is None:
                    m[row][c] = bits[idx] if idx < len(bits) else 0
                    idx += 1
        upward = not upward
        col -= 2


_MASKS = (
    lambda r, c: (r + c) % 2 == 0,
    lambda r, c: r % 2 == 0,
    lambda r, c: c % 3 == 0,
    lambda r, c: (r + c) % 3 == 0,
    lambda r, c: (r // 2 + c // 3) % 2 == 0,
    lambda r, c: (r * c) % 2 + (r * c) % 3 == 0,
    lambda r, c: ((r * c) % 2 + (r * c) % 3) % 2 == 0,
    lambda r, c: ((r + c) % 2 + (r * c) % 3) % 2 == 0,
)


_N3_CORE = [1, 0, 1, 1, 1, 0, 1]


def _find(seq, sub, start):
    """Index of `sub` in `seq` at or after `start`, or -1."""
    end = len(seq) - len(sub)
    for i in range(start, end + 1):
        if seq[i:i + len(sub)] == sub:
            return i
    return -1


def _n3_occurrences(seq, size):
    """Rule 3 for one row or column.

    The pattern is the seven-module finder core, counted when it has a
    four-module light run on at least one side - or when it sits hard
    against the symbol edge, where the quiet zone supplies one. A run is
    "light" if it holds no dark module, and it is clipped at the border
    rather than padded.

    Written this way rather than as an eleven-module window match because
    the two are not the same: a window match misses a core against the
    edge, and it misses one whose light run is shortened by the border.
    Those are exactly the lookalikes a scanner is most likely to lock
    onto, and under-counting them chose masks here that OpenCV could not
    read at all."""
    count = 0
    idx = _find(seq, _N3_CORE, 0)
    while idx != -1:
        offset = idx + 7
        if (idx in (0, size - 7)
                or not any(seq[max(idx - 4, 0):idx])
                or not any(seq[offset:min(offset + 4, size)])):
            count += 40
        else:
            # No light run either side: the next possible match starts
            # inside this one, at its middle dark module.
            offset = idx + 4
        idx = _find(seq, _N3_CORE, offset)
    return count


def _penalty(m):
    """The four scoring rules, summed. Lower is better.

    Worth getting exactly right rather than approximately: the mask with
    the lowest score is the one that ships. This follows ISO/IEC 18004
    table 11, cross-checked against segno's implementation of the same
    table - an approximation of rules 3 and 4 picked masks whose symbols
    were structurally valid and would not scan."""
    size = len(m)
    rows = [list(row) for row in m]
    cols = [list(col) for col in zip(*m)]
    score = 0

    # Rule 1: runs of five or more of the same colour, each way.
    for line in rows + cols:
        run, prev = 1, line[0]
        for cell in line[1:]:
            if cell == prev:
                run += 1
            else:
                if run >= 5:
                    score += run - 2
                run, prev = 1, cell
        if run >= 5:
            score += run - 2

    # Rule 2: every 2x2 block of one colour.
    for r in range(size - 1):
        for c in range(size - 1):
            if m[r][c] == m[r][c + 1] == m[r + 1][c] == m[r + 1][c + 1]:
                score += 3

    # Rule 3: finder lookalikes in the data.
    for line in rows + cols:
        score += _n3_occurrences(line, size)

    # Rule 4: drift away from half dark, in five-percent steps.
    dark = sum(sum(row) for row in m)
    percent = dark * 100.0 / (size * size)
    score += 10 * int(abs(percent - 50) / 5)
    return score


def _format_bits(ecl, mask):
    """Fifteen bits: five of data, ten of BCH, xored with the mask the
    specification fixes so an all-zero format is never all-zero."""
    data = (ECC_LEVELS[ecl] << 3) | mask
    rem = data
    for _ in range(10):
        rem = (rem << 1) ^ (0x537 if (rem >> 9) & 1 else 0)
    # 0x537 is the generator shifted up; fold it the standard way.
    value = ((data << 10) | (rem & 0x3FF)) ^ 0x5412
    return value


def _version_bits(version):
    rem = version
    for _ in range(12):
        rem = (rem << 1) ^ (0x1F25 if (rem >> 11) & 1 else 0)
    return (version << 12) | (rem & 0xFFF)


def _apply_format(m, ecl, mask, version):
    """Write the two copies of the format field.

    The first copy runs *down column 8* and along row 8, in that order -
    not the other way round. Writing it transposed puts a well-formed
    format string in the wrong place, which every scanner reads as a
    different mask and error level, so the symbol decodes to noise rather
    than failing outright."""
    size = len(m)
    bits = _format_bits(ecl, mask)

    def bit(i):
        return (bits >> i) & 1

    # Copy one: bits 0-5 down column 8, then across the corner into row 8.
    for i in range(6):
        m[i][8] = bit(i)
    m[7][8] = bit(6)
    m[8][8] = bit(7)
    m[8][7] = bit(8)
    for i in range(9, 15):
        m[8][14 - i] = bit(i)

    # Copy two: bits 0-7 leftwards along row 8 from the right edge, then
    # 8-14 upwards from the bottom of column 8.
    for i in range(8):
        m[8][size - 1 - i] = bit(i)
    for i in range(8, 15):
        m[size - 15 + i][8] = bit(i)

    # Always dark, and not part of either copy.
    m[size - 8][8] = 1

    if version >= 7:
        vbits = _version_bits(version)
        for i in range(18):
            b = (vbits >> i) & 1
            r, c = i // 3, i % 3
            m[size - 11 + c][r] = b
            m[r][size - 11 + c] = b


def encode(text, ecl="M", version=None, mask=None):
    """Build a QR symbol and return it as a list of rows of 0/1.

    No quiet zone: the caller decides the margin, because on a 48mm label
    the four-module border the specification asks for is a real fraction
    of the width and the layout has to account for it deliberately rather
    than inherit it. `render` adds it.
    """
    if ecl not in ECC_LEVELS:
        raise QRError(f"unknown error-correction level {ecl!r}")
    mode = pick_mode(text)
    if version is None:
        version = choose_version(text, ecl, mode)
    if not 1 <= version <= MAX_VERSION:
        raise QRError(f"version {version} is outside 1-{MAX_VERSION}")

    codewords = _codewords(text, version, ecl, mode)
    size = version * 4 + 17

    base = _new_matrix(size)
    _place_finder(base, 0, 0)
    _place_finder(base, 0, size - 7)
    _place_finder(base, size - 7, 0)
    _place_alignment(base, version)
    _place_timing(base)
    _reserve_format(base, version)

    # Whatever is still empty at this point is a data module, and those
    # are exactly the ones masking may touch. Recorded rather than
    # re-derived from the version: a second description of which modules
    # are functional is a second thing to get wrong, and the failure is a
    # symbol that looks perfect and does not scan.
    is_data = [[base[r][c] is None for c in range(size)] for r in range(size)]
    _place_data(base, codewords)

    candidates = []
    for candidate in (range(8) if mask is None else [mask]):
        m = [row[:] for row in base]
        for r in range(size):
            for c in range(size):
                if is_data[r][c] and _MASKS[candidate](r, c):
                    m[r][c] ^= 1
        _apply_format(m, ecl, candidate, version)
        candidates.append((_penalty(m), candidate, m))

    candidates.sort(key=lambda t: (t[0], t[1]))
    return candidates[0][2]


def render(text, ecl="M", quiet=4, scale=1, version=None):
    """`encode`, plus the quiet zone and an optional integer scale.

    The quiet zone is not decoration - a symbol printed hard against
    other ink is a symbol that will not scan - and four modules is what
    the specification asks for."""
    matrix = encode(text, ecl=ecl, version=version)
    size = len(matrix) + 2 * quiet
    out = [[0] * size for _ in range(size)]
    for r, row in enumerate(matrix):
        for c, cell in enumerate(row):
            out[r + quiet][c + quiet] = cell
    if scale == 1:
        return out
    return [[cell for cell in row for _ in range(scale)]
            for row in out for _ in range(scale)]
